builds:
  - binary: "kafka"
    main: ./cmd/vault-plugin-secrets-kafka/
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: "arm64"
      - goos: windows
        goarch: "arm64"
    ldflags:
      - "-s -w -X version.version={{.Version}} -X version.commit={{.Commit}} -X
        version.date={{.Date}} -X version.builtBy=goreleaser"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "-u"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
snapshot:
  version_template: "{{ .Version }}-next"
