name: test

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: "Run tests"
        run: |
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0
          make test | tee results | go-junit-report -set-exit-code > report.xml
          cat results
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "report.xml"
        if: always()

  acctest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/cache@v3.3.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go
      - name: Bring up kafka
        run: make upkafka
      - name: "Run tests"
        run: |
          go install github.com/jstemmer/go-junit-report/v2@v2.1.0
          make testacc | tee results | go-junit-report -set-exit-code > report.xml
          cat results
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "report.xml"
        if: always()
